In [26]:
import pandas as pd
df = pd.read_csv("logisticcodedata2.csv")
df

input1  input2  output
0   4.5192  2.6487       1
1   2.4443  1.5438       1
2   4.2409  1.8990       1
3   5.8097  2.4711       1
4   6.4423  3.3590       1
5   5.8097  3.2406       1
6   6.3917  3.8128       1
7   6.8725  4.4441       1
8   6.7966  3.6747       1
9   8.1630  4.7401       1
10  7.4038  3.8917       1
11  7.6316  4.6020       1
12  7.7581  5.7265       1
13  6.5688  4.9571       1
14  5.3543  3.9903       1
15  4.4686  3.0236       1
16  2.9757  2.0568       1
17  2.4443  1.2676       1
18  0.9008  1.1690       1
19  2.1154  1.7411       1
20  3.2794  1.3860       1
21  4.1650  1.5636       1
22  4.8482  1.8793       1
23  3.3300  2.7868       1
24  5.1518  3.5563       1
25  6.2652  4.0693       1
26  6.2652  4.3849       1
27  7.2014  1.5438       1
28  7.6569  2.4120       1
29  6.1387  1.7806       1
..     ...     ...     ...
70  7.7581  7.7784       0
71  5.1012  7.6009       0
72  4.2156  6.4960       0
73  3.4818  5.8055       0
74  2.3684  5.0163       0
75  1.7864  4.1876       0
76  0.9008  3.4379       0
77  0.9008  5.7857       0
78  1.9636  6.3382       0
79  1.4069  4.9571       0
80  2.4190  6.8511       0
81  2.8745  6.0817       0
82  4.0132  7.1668       0
83  4.6711  7.2260       0
84  5.1771  8.1533       0
85  6.2146  7.4825       0
86  5.4555  7.0484       0
87  5.9868  8.5084       0
88  4.0891  7.5417       0
89  2.3937  7.2063       0
90  1.3310  6.5355       0
91  1.7358  5.4503       0
92  2.4443  5.8449       0
93  3.1781  4.8979       0
94  4.6711  5.8055       0
95  5.9868  7.3641       0
96  4.6711  6.2592       0
97  7.5810  8.3703       0
98  4.6457  8.5676       0
99  4.6457  8.1676       0

[100 rows x 3 columns]

In [27]:
x1 = df.iloc[:,:-2]
x2 = df.iloc[:,1]
y = df.iloc[:,2]
x1

input1
0   4.5192
1   2.4443
2   4.2409
3   5.8097
4   6.4423
5   5.8097
6   6.3917
7   6.8725
8   6.7966
9   8.1630
10  7.4038
11  7.6316
12  7.7581
13  6.5688
14  5.3543
15  4.4686
16  2.9757
17  2.4443
18  0.9008
19  2.1154
20  3.2794
21  4.1650
22  4.8482
23  3.3300
24  5.1518
25  6.2652
26  6.2652
27  7.2014
28  7.6569
29  6.1387
..     ...
70  7.7581
71  5.1012
72  4.2156
73  3.4818
74  2.3684
75  1.7864
76  0.9008
77  0.9008
78  1.9636
79  1.4069
80  2.4190
81  2.8745
82  4.0132
83  4.6711
84  5.1771
85  6.2146
86  5.4555
87  5.9868
88  4.0891
89  2.3937
90  1.3310
91  1.7358
92  2.4443
93  3.1781
94  4.6711
95  5.9868
96  4.6711
97  7.5810
98  4.6457
99  4.6457

[100 rows x 1 columns]

In [28]:
x2

0     2.6487
1     1.5438
2     1.8990
3     2.4711
4     3.3590
5     3.2406
6     3.8128
7     4.4441
8     3.6747
9     4.7401
10    3.8917
11    4.6020
12    5.7265
13    4.9571
14    3.9903
15    3.0236
16    2.0568
17    1.2676
18    1.1690
19    1.7411
20    1.3860
21    1.5636
22    1.8793
23    2.7868
24    3.5563
25    4.0693
26    4.3849
27    1.5438
28    2.4120
29    1.7806
       ...  
70    7.7784
71    7.6009
72    6.4960
73    5.8055
74    5.0163
75    4.1876
76    3.4379
77    5.7857
78    6.3382
79    4.9571
80    6.8511
81    6.0817
82    7.1668
83    7.2260
84    8.1533
85    7.4825
86    7.0484
87    8.5084
88    7.5417
89    7.2063
90    6.5355
91    5.4503
92    5.8449
93    4.8979
94    5.8055
95    7.3641
96    6.2592
97    8.3703
98    8.5676
99    8.1676
Name: input2, Length: 100, dtype: float64

In [29]:
y

0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    1
21    1
22    1
23    1
24    1
25    1
26    1
27    1
28    1
29    1
     ..
70    0
71    0
72    0
73    0
74    0
75    0
76    0
77    0
78    0
79    0
80    0
81    0
82    0
83    0
84    0
85    0
86    0
87    0
88    0
89    0
90    0
91    0
92    0
93    0
94    0
95    0
96    0
97    0
98    0
99    0
Name: output, Length: 100, dtype: int64

In [30]:
import numpy as np

x1 = np.array(x1)
x2 = np.array(x2)
y = np.array(y)
print(x1)
print(x2)
print(y)



[[4.5192]
 [2.4443]
 [4.2409]
 [5.8097]
 [6.4423]
 [5.8097]
 [6.3917]
 [6.8725]
 [6.7966]
 [8.163 ]
 [7.4038]
 [7.6316]
 [7.7581]
 [6.5688]
 [5.3543]
 [4.4686]
 [2.9757]
 [2.4443]
 [0.9008]
 [2.1154]
 [3.2794]
 [4.165 ]
 [4.8482]
 [3.33  ]
 [5.1518]
 [6.2652]
 [6.2652]
 [7.2014]
 [7.6569]
 [6.1387]
 [4.4939]
 [4.8735]
 [5.5314]
 [6.0121]
 [7.1508]
 [7.7075]
 [8.3148]
 [8.5172]
 [8.7449]
 [7.8593]
 [6.999 ]
 [5.5061]
 [4.9241]
 [6.6447]
 [7.6822]
 [8.0364]
 [8.9221]
 [7.8593]
 [6.5941]
 [6.0374]
 [2.7227]
 [1.9383]
 [1.6852]
 [4.3168]
 [3.4312]
 [5.4808]
 [4.1144]
 [3.2034]
 [4.1144]
 [5.1012]
 [4.8988]
 [5.9615]
 [5.7591]
 [6.6953]
 [5.7338]
 [6.6194]
 [7.2014]
 [7.2014]
 [8.5931]
 [7.7581]
 [7.7581]
 [5.1012]
 [4.2156]
 [3.4818]
 [2.3684]
 [1.7864]
 [0.9008]
 [0.9008]
 [1.9636]
 [1.4069]
 [2.419 ]
 [2.8745]
 [4.0132]
 [4.6711]
 [5.1771]
 [6.2146]
 [5.4555]
 [5.9868]
 [4.0891]
 [2.3937]
 [1.331 ]
 [1.7358]
 [2.4443]
 [3.1781]
 [4.6711]
 [5.9868]
 [4.6711]
 [7.581 ]
 [4.6457]
 [4.6457]]

In [33]:
import random
w0 = random.random()
w1 = random.random()
w2 = random.random()
yp = w0 + (w1 * x1)+ (w2 * x2) #choose model or hypohesis                                                                                                                                                                
print(yp)

[[3.8236781  2.72627332 3.07906378 ... 9.50646496 9.70242655 9.30513999]
 [3.72228346 2.62487868 2.97766914 ... 9.40507032 9.60103191 9.20374536]
 [3.81007835 2.71267356 3.06546402 ... 9.4928652  9.68882679 9.29154024]
 ...
 [3.97329982 2.87589504 3.22868549 ... 9.65608667 9.85204827 9.45476171]
 [3.8298598  2.73245502 3.08524548 ... 9.51264666 9.70860825 9.3113217 ]
 [3.8298598  2.73245502 3.08524548 ... 9.51264666 9.70860825 9.3113217 ]]


In [34]:
z = 1/(1 +np.exp(-yp))
z

array([[0.9786198 , 0.93855929, 0.95602084, ..., 0.99992564, 0.99993887,
        0.99990905],
       [0.97639211, 0.93244567, 0.95155504, ..., 0.9999177 , 0.99993235,
        0.99989935],
       [0.97833339, 0.93777035, 0.95544548, ..., 0.99992462, 0.99993803,
        0.99990781],
       ...,
       [0.98153607, 0.9466419 , 0.96189961, ..., 0.99993597, 0.99994736,
        0.99992169],
       [0.97874876, 0.93891479, 0.95628002, ..., 0.99992609, 0.99993925,
        0.99990961],
       [0.97874876, 0.93891479, 0.95628002, ..., 0.99992609, 0.99993925,
        0.99990961]])

In [35]:
error = -1* sum(y*np.log(z) +(1-y)*np.log(1-z))

In [36]:
error

array([2.10760553e+00, 6.18555736e+00, 4.38676119e+00, 2.50906872e+00,
       1.04649487e+00, 1.17631421e+00, 6.68071353e-01, 3.57433227e-01,
       7.65908864e-01, 2.66511188e-01, 6.17873746e-01, 3.05631956e-01,
       1.00137938e-01, 2.14894931e-01, 5.60396036e-01, 1.45716355e+00,
       3.76232501e+00, 8.06041107e+00, 8.85369093e+00, 5.11268470e+00,
       7.19782042e+00, 6.06871855e+00, 4.47151077e+00, 1.83996394e+00,
       8.61072308e-01, 5.18216435e-01, 3.79038480e-01, 6.18555736e+00,
       2.65873744e+00, 4.92079373e+00, 7.06321020e+00, 2.19079265e+00,
       1.37453003e+00, 5.94232704e-01, 2.61354033e-01, 1.51075648e-01,
       1.02115546e-01, 1.83750179e-01, 1.36978159e-01, 6.68071353e-01,
       1.17631421e+00, 1.63750711e+00, 2.02734556e+00, 6.55169439e-01,
       3.24111177e-01, 9.44224714e-02, 4.39808373e-02, 1.60217599e-01,
       1.63380733e-01, 2.61354033e-01, 5.77772239e+02, 4.86140652e+02,
       4.20249660e+02, 5.62152075e+02, 4.95871023e+02, 6.46209170e+02,
      

In [24]:
dj0 = -1*sum(y*(1-z) -(1-y)*z)

In [37]:
dj0

array([-0.95632697, -1.61780567, -1.3683309 , -1.04156527, -0.67792454,
       -0.71812613, -0.54317536, -0.39837129, -0.5811427 , -0.34427485,
       -0.52258393, -0.36854805, -0.21126999, -0.30928232, -0.49792288,
       -0.79789533, -1.2695797 , -1.84061865, -1.92684856, -1.47438929,
       -1.74181273, -1.60284281, -1.38115803, -0.89472389, -0.61574774,
       -0.47899007, -0.4101543 , -1.61780567, -1.07151223, -1.44715316,
       -1.72586042, -0.9746379 , -0.77531962, -0.51258925, -0.34094325,
       -0.25944586, -0.21334554, -0.28606471, -0.24706456, -0.54317536,
       -0.71812613, -0.84497058, -0.93830195, -0.53796088, -0.37946258,
       -0.20515251, -0.13994231, -0.26716464, -0.26978325, -0.34094325,
       99.62783634, 99.4132055 , 99.18668891, 99.59774512, 99.4408555 ,
       99.73544193, 99.67208433, 99.59774512, 99.75049946, 99.82289679,
       99.77152611, 99.85301226, 99.81581549, 99.87438891, 99.86676063,
       99.89579115, 99.91355544, 99.87803851, 99.91770873, 99.89

In [9]:
import pandas as pd
df = pd.read_csv("logisticcodedata2.csv")
df

input1  input2  output
0   4.5192  2.6487       1
1   2.4443  1.5438       1
2   4.2409  1.8990       1
3   5.8097  2.4711       1
4   6.4423  3.3590       1
5   5.8097  3.2406       1
6   6.3917  3.8128       1
7   6.8725  4.4441       1
8   6.7966  3.6747       1
9   8.1630  4.7401       1
10  7.4038  3.8917       1
11  7.6316  4.6020       1
12  7.7581  5.7265       1
13  6.5688  4.9571       1
14  5.3543  3.9903       1
15  4.4686  3.0236       1
16  2.9757  2.0568       1
17  2.4443  1.2676       1
18  0.9008  1.1690       1
19  2.1154  1.7411       1
20  3.2794  1.3860       1
21  4.1650  1.5636       1
22  4.8482  1.8793       1
23  3.3300  2.7868       1
24  5.1518  3.5563       1
25  6.2652  4.0693       1
26  6.2652  4.3849       1
27  7.2014  1.5438       1
28  7.6569  2.4120       1
29  6.1387  1.7806       1
..     ...     ...     ...
70  7.7581  7.7784       0
71  5.1012  7.6009       0
72  4.2156  6.4960       0
73  3.4818  5.8055       0
74  2.3684  5.0163       0
75  1.7864  4.1876       0
76  0.9008  3.4379       0
77  0.9008  5.7857       0
78  1.9636  6.3382       0
79  1.4069  4.9571       0
80  2.4190  6.8511       0
81  2.8745  6.0817       0
82  4.0132  7.1668       0
83  4.6711  7.2260       0
84  5.1771  8.1533       0
85  6.2146  7.4825       0
86  5.4555  7.0484       0
87  5.9868  8.5084       0
88  4.0891  7.5417       0
89  2.3937  7.2063       0
90  1.3310  6.5355       0
91  1.7358  5.4503       0
92  2.4443  5.8449       0
93  3.1781  4.8979       0
94  4.6711  5.8055       0
95  5.9868  7.3641       0
96  4.6711  6.2592       0
97  7.5810  8.3703       0
98  4.6457  8.5676       0
99  4.6457  8.1676       0

[100 rows x 3 columns]

In [16]:
x = df.iloc[:,:2]
y = df.iloc[:,2]

In [17]:
y

0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    1
21    1
22    1
23    1
24    1
25    1
26    1
27    1
28    1
29    1
     ..
70    0
71    0
72    0
73    0
74    0
75    0
76    0
77    0
78    0
79    0
80    0
81    0
82    0
83    0
84    0
85    0
86    0
87    0
88    0
89    0
90    0
91    0
92    0
93    0
94    0
95    0
96    0
97    0
98    0
99    0
Name: output, Length: 100, dtype: int64

In [13]:
x

input1  input2
0   4.5192  2.6487
1   2.4443  1.5438
2   4.2409  1.8990
3   5.8097  2.4711
4   6.4423  3.3590
5   5.8097  3.2406
6   6.3917  3.8128
7   6.8725  4.4441
8   6.7966  3.6747
9   8.1630  4.7401
10  7.4038  3.8917
11  7.6316  4.6020
12  7.7581  5.7265
13  6.5688  4.9571
14  5.3543  3.9903
15  4.4686  3.0236
16  2.9757  2.0568
17  2.4443  1.2676
18  0.9008  1.1690
19  2.1154  1.7411
20  3.2794  1.3860
21  4.1650  1.5636
22  4.8482  1.8793
23  3.3300  2.7868
24  5.1518  3.5563
25  6.2652  4.0693
26  6.2652  4.3849
27  7.2014  1.5438
28  7.6569  2.4120
29  6.1387  1.7806
..     ...     ...
70  7.7581  7.7784
71  5.1012  7.6009
72  4.2156  6.4960
73  3.4818  5.8055
74  2.3684  5.0163
75  1.7864  4.1876
76  0.9008  3.4379
77  0.9008  5.7857
78  1.9636  6.3382
79  1.4069  4.9571
80  2.4190  6.8511
81  2.8745  6.0817
82  4.0132  7.1668
83  4.6711  7.2260
84  5.1771  8.1533
85  6.2146  7.4825
86  5.4555  7.0484
87  5.9868  8.5084
88  4.0891  7.5417
89  2.3937  7.2063
90  1.3310  6.5355
91  1.7358  5.4503
92  2.4443  5.8449
93  3.1781  4.8979
94  4.6711  5.8055
95  5.9868  7.3641
96  4.6711  6.2592
97  7.5810  8.3703
98  4.6457  8.5676
99  4.6457  8.1676

[100 rows x 2 columns]

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 1/3, random_state = 0 )

In [20]:
from sklearn.linear_model import LogisticRegression

In [21]:
k = LogisticRegression()

In [22]:
k.fit(x_train,y_train)

C:\anaconda\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [23]:
l = k.predict(x_test)

In [24]:
l

array([1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [26]:
from sklearn import datasets, linear_model, metrics 
print("Logistic Regression model accuracy(in %):",  
metrics.accuracy_score(y_test, l)*100)

Logistic Regression model accuracy(in %): 100.0


In [28]:
from sklearn.metrics import confusion_matrix 
results = confusion_matrix(y_test, l) 
print ('Confusion Matrix :')
print(results)

Confusion Matrix :
[[19  0]
 [ 0 15]]
