In [142]:
import pandas as pd
import random 
import numpy as np
import matplotlib.pyplot as pl

In [143]:

dataset = pd.read_csv("logisticcodedata2.csv")
#dataset

In [144]:
x1=dataset.iloc[:,0]
x2=dataset.iloc[:,1]
y=dataset.iloc[:,-1]

In [145]:
x1=np.array(x1)
x2=np.array(x2)
y=np.array(y)
#print(x1)
##print(x2)
#print(y)

In [146]:
w0=random.random()
w1=random.random()
w2=random.random()
yp=w0+(w1*x1)+(w2*x2)
print(yp)
print(y)

[ 5.65955652  3.41651228  4.8839487   6.37206387  7.49085019  6.97941578
  7.81559262  8.63154919  7.97412611  9.71786014  8.54660087  9.25774369
 10.22887393  8.83578403  7.27023939  5.92202466  4.17253027  3.1985128
  2.100839    3.35492041  3.84374685  4.56907368  5.26966666  4.98280542
  6.79389168  7.93445978  8.18355694  6.55971385  7.54593445  6.0444483
  4.66176323  5.86255867  6.67098354  7.65814806  9.06460895  9.86844132
 10.5811585  10.24771651 10.63179403  8.7852932   7.7652327   6.51409049
  5.95826635  7.99830843  9.24445163 10.45948305 11.65205152  9.92201605
  9.07050021  8.32894213  5.99861416  4.74842998  4.05174708  6.92734965
  5.81274932  8.36607607  7.12061529  6.19168283  7.55661425  8.75370914
  8.21507429  9.61796553  9.12613505 10.35199191  9.62324044 10.59774336
 11.27811607 10.73311737 12.27556862 11.38122455 11.84840012  9.95278521
  8.49555789  7.4657089   6.10714132  5.06851384  3.89163922  5.74471373
  6.88302505  5.42511531  7.58874795  7.28244158  8.8

In [147]:
z = 1/(1 +np.exp(-yp))
z

array([0.99652803, 0.96821662, 0.99248976, 0.99829429, 0.99944214,
       0.99907002, 0.99959677, 0.99982164, 0.99965586, 0.9999398 ,
       0.99980583, 0.99990464, 0.99996389, 0.99985459, 0.99930454,
       0.99732739, 0.98482075, 0.96077827, 0.8909847 , 0.96626559,
       0.97903569, 0.98973882, 0.99488101, 0.99319186, 0.99888066,
       0.99964194, 0.99972087, 0.99858571, 0.99947203, 0.99763462,
       0.99063868, 0.99716411, 0.99873445, 0.99952804, 0.99988432,
       0.99994822, 0.99997461, 0.99996456, 0.99997586, 0.99984706,
       0.99957595, 0.99851979, 0.99742227, 0.99966408, 0.99990336,
       0.99997133, 0.9999913 , 0.99995092, 0.999885  , 0.99975863,
       0.99752396, 0.99140915, 0.98290535, 0.99902036, 0.99701971,
       0.99976743, 0.99919238, 0.9979578 , 0.99947763, 0.99984215,
       0.99972953, 0.99993348, 0.99989123, 0.99996807, 0.99993383,
       0.99997503, 0.99998735, 0.99997819, 0.99999534, 0.99998859,
       0.99999285, 0.99995241, 0.99979567, 0.99942795, 0.99777

In [148]:
error = -1* sum(y*np.log(z) +(1-y)*np.log(1-z))

In [149]:
error

418.2206701185172

In [150]:
dj0 = sum(z-y)

In [151]:
dj0

49.59990528196135

In [152]:
dj1 = sum((z-y)*x1)

In [153]:
dj1

215.66774484328673

In [154]:
dj2 = sum((z-y)* x2)

In [155]:
dj2

310.26244198229443

In [156]:
alpha = 0.001

In [157]:
w0 = w0 + (alpha*dj0)
w1 = w1 + (alpha*dj1)
w2 = w2 + (alpha*dj2)

In [158]:
w0

0.6325754236636401

In [159]:
w1

0.8764067603707244

In [160]:
w2

1.0995436885977266

In [161]:
yp1=w0+(w1*x1)+(w2*x2)

In [162]:
yp1

array([ 7.50559422,  4.47225201,  6.43736232,  8.44131819,  9.97201795,
        9.28741706, 10.42664469, 11.54216299, 10.6296548 , 12.99863085,
       11.40040997, 12.38106131, 13.72836364, 11.84006417,  9.71262932,
        7.87346697,  5.50204048,  4.16855805,  2.70740921,  4.4009418 ,
        5.03063131,  6.00205609,  6.94794313,  6.61521829,  9.05795499,
       10.59781219, 10.94482818,  8.64140661,  9.99523372,  7.9704211 ,
        6.11668833,  7.77278312,  8.87000506, 10.2240367 , 12.13319293,
       13.22847651, 14.19459828, 13.7211631 , 14.24618585, 11.71285925,
       10.32972762,  8.65255301,  7.9038833 , 10.67003661, 12.36031451,
       14.03736063, 15.65969297, 13.29642207, 12.16593123, 11.15740165,
        8.0570972 ,  6.35003687,  5.39064442,  9.28066922,  7.76694949,
       11.23365956,  9.55882544,  8.30487794, 10.16621338, 11.79039644,
       11.0489458 , 12.95647815, 12.28023045, 13.94671137, 12.9738603 ,
       14.29241103, 15.21458874, 14.45535382, 16.54280899, 15.33

In [163]:
z = 1/(1 +np.exp(-yp1))
z

array([0.9994503 , 0.98870741, 0.99840193, 0.99978428, 0.99995331,
       0.99990743, 0.99997037, 0.99999029, 0.99997581, 0.99999774,
       0.99998881, 0.9999958 , 0.99999891, 0.99999279, 0.99993949,
       0.99961943, 0.99593813, 0.98476126, 0.93746243, 0.98788284,
       0.99350774, 0.99753244, 0.99904031, 0.99866197, 0.99988355,
       0.99997503, 0.99998235, 0.99982339, 0.99995439, 0.99965459,
       0.99779911, 0.99957914, 0.99985948, 0.99996371, 0.99999462,
       0.9999982 , 0.99999932, 0.9999989 , 0.99999935, 0.99999181,
       0.99996735, 0.99982535, 0.99963083, 0.99997677, 0.99999571,
       0.9999992 , 0.99999984, 0.99999832, 0.9999948 , 0.99998573,
       0.99968326, 0.99825636, 0.99546166, 0.9999068 , 0.99957668,
       0.99998678, 0.99992943, 0.99975275, 0.99996155, 0.99999242,
       0.9999841 , 0.99999764, 0.99999536, 0.99999912, 0.99999768,
       0.99999938, 0.99999975, 0.99999947, 0.99999993, 0.99999978,
       0.99999989, 0.99999857, 0.99998956, 0.99995756, 0.99973

In [164]:
error = -1* sum(y*np.log(z) +(1-y)*np.log(1-z))
error

563.670524779947